
package scoutcoding;

import java.util.ArrayList;

import javax.swing.JOptionPane;

/**
 *
 * @author ANTONIO
 */
public class Fenetre
  extends javax.swing.JFrame
{

  /** Creates new form Fenetre */
  public Fenetre()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents()//GEN-BEGIN:initComponents
  {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTextAreaIn = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextArreaOut = new javax.swing.JTextArea();
    jScrollPane3 = new javax.swing.JScrollPane();
    listOfCode = new javax.swing.JComboBox<>();
    jButton1 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTextAreaIn.setColumns(20);
    jTextAreaIn.setRows(5);
    jTextAreaIn.setName("texteIn"); // NOI18N
    jTextAreaIn.addKeyListener(new java.awt.event.KeyAdapter()
    {
      public void keyReleased(java.awt.event.KeyEvent evt)
      {
        jTextAreaInKeyReleased(evt);
      }
    });
    jScrollPane1.setViewportView(jTextAreaIn);

    jTextArreaOut.setColumns(20);
    jTextArreaOut.setRows(5);
    jTextArreaOut.setName("textOut"); // NOI18N
    jScrollPane2.setViewportView(jTextArreaOut);

    listOfCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seletionar o codigo", "Alfabeto Numeral", "Vogais por Pontos", "Caranguejo", "Alfabeto Invertido", "TX Code", "Morse Code", "Romano-Árabe" }));
    listOfCode.addItemListener(new java.awt.event.ItemListener()
    {
      public void itemStateChanged(java.awt.event.ItemEvent evt)
      {
        listOfCodeItemStateChanged(evt);
      }
    });
    jScrollPane3.setViewportView(listOfCode);

    jButton1.setText("Traduçao");
    jButton1.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        jButton1MouseClicked(evt);
      }
    });

    jLabel1.setText(" Code SCout");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(33, 33, 33))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(47, 47, 47))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
              .addContainerGap()
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(18, 18, 18)
              .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addGap(33, 33, 33)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(68, Short.MAX_VALUE))
    );

    pack();
  }//GEN-END:initComponents

/****          start my work ******************/
  int n;
  Metier m = new Metier();
  
  public void takeWords()
  {
    
    m.setTextIn(jTextAreaIn.getText());
    // my msmboxJOptionPane.showMessageDialog(null, "Correct");
    //m.setTextIn(jTextArreaOut.getText());
  }
  private void jButton1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton1MouseClicked
  {//GEN-HEADEREND:event_jButton1MouseClicked
    // TODO add your handling code here:
    /************************************/
    if(!m.tesTextOut().isEmpty())
    {
      /*************** testar si a liste est vide ************/
      ArrayList<String> vide = new ArrayList<String>();
      m.setTextCodeOut(vide);}
    
    takeWords();
    if(chooseCode()==1)
    {
      m.setCode(6);m.translation();
      jTextArreaOut.setText(m.getTextOut());
    }
    else  if(chooseCode()==2)
    {
      m.setCode(5);m.translation();
      jTextArreaOut.setText(m.getTextOut());
    }
    else if(chooseCode()==3)
    {
      m.caranguejo();
      jTextArreaOut.setText(m.getTextOut());
    }
    else if(chooseCode()==4)
    {
      m.setCode(2);m.translation();
      jTextArreaOut.setText(m.getTextOut());
    }
    else  if(chooseCode()==5)
    {
      m.setCode(1);m.translation();
      jTextArreaOut.setText(m.getTextOut());
    }
    else  if(chooseCode()==6)
    {
      m.setCode(3);m.translation();
      jTextArreaOut.setText(m.getTextOut());
    }
    else if(chooseCode()==7)
    {
       m.setCode(4);m.translation();
      jTextArreaOut.setText(m.getTextOut());
      
    }
    
  }//GEN-LAST:event_jButton1MouseClicked

  public Integer chooseCode(){ return n;}
  
  private void listOfCodeItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_listOfCodeItemStateChanged
  {//GEN-HEADEREND:event_listOfCodeItemStateChanged
    // ecrire 
    
    String codeSlect = listOfCode.getSelectedItem().toString();
    if(codeSlect.equals("Alfabeto Numeral"))
    {
      n=1;
      jLabel1.setText(" Scout Code Alfabeto Numeral");
    }
    else if(codeSlect.equals("Vogais por Pontos"))
    {
      n=2;
      jLabel1.setText(" Scout Code Vogais por Pontos");
    }
    
    else if(codeSlect.equals("Caranguejo"))
    {
      n=3;
      jLabel1.setText(" Scout Code Caranguejo");
    }
    
    else if(codeSlect.equals("Alfabeto Invertido"))
    {
      n=4;
      jLabel1.setText("Scout Code Alfabeto Invertido ");
    }
    else if(codeSlect.equals("TX Code"))
    {
      n=5;
      jLabel1.setText("Scout TX Code");
    }
    else if(codeSlect.equals("Morse Code"))
    {
      n=6;
      jLabel1.setText("Scout Morse Code");
    }
    else if(codeSlect.equals("Romano-Árabe"))
    {
      n=7;
      jLabel1.setText("Scout Code Romano-Árabe");
    }
    
    jTextArreaOut.setText("");
  }//GEN-LAST:event_listOfCodeItemStateChanged

  private void jTextAreaInKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextAreaInKeyReleased
  {//GEN-HEADEREND:event_jTextAreaInKeyReleased
    // TODO add your handling code here:
    if(!jTextAreaIn.getText().isEmpty())
    {takeWords();}
    else
    {jTextArreaOut.setText("");}
  }//GEN-LAST:event_jTextAreaInKeyReleased

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info: javax.swing
                                                            .UIManager
                                                            .getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing
               .UIManager
               .setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util
          .logging
          .Logger
          .getLogger(Fenetre.class.getName())
          .log(java.util
                   .logging
                   .Level
                   .SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util
          .logging
          .Logger
          .getLogger(Fenetre.class.getName())
          .log(java.util
                   .logging
                   .Level
                   .SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util
          .logging
          .Logger
          .getLogger(Fenetre.class.getName())
          .log(java.util
                   .logging
                   .Level
                   .SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util
          .logging
          .Logger
          .getLogger(Fenetre.class.getName())
          .log(java.util
                   .logging
                   .Level
                   .SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt
        .EventQueue
        .invokeLater(new Runnable()
      {
        public void run()
        {
          new Fenetre().setVisible(true);
        }
      });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTextArea jTextAreaIn;
  private javax.swing.JTextArea jTextArreaOut;
  private javax.swing.JComboBox<String> listOfCode;
  // End of variables declaration//GEN-END:variables

}
